---
title: Математические методы в зоологии с использованием R
description: Презентации к курсу Математические методы в зоологии с использованием R
---
 
## О курсе

### Цель и задачи курса

Цели этого курса: познакомить с применением различных математических методов в биологии (анализ мощности, регрессионный и дисперсионный анализ, анализ клавных компонент, многомерное шкалирование, кластерный анализ), и научить самостоятельно анализировать данные с использованием скриптов на языке статистического программирования R, представлять в наглядном виде результаты анализов, интерпретировать их и представлять в виде научного отчета.

### Расписание и контакты

1-я пара по субботам, с 23 сентября.

Варфоломеева Марина Александровна -  marina.varfolomeeva[]gmail.com

### Задания, дедлайны и оценки

(1) Короткие тесты (10 минут) в начале каждой лекции, кроме самой первой --- 32 баллов. Каждый тест из 2 вопросов, каждый правильный ответ приносит 2 баллa.

(2) Домашние задания по анализу данных --- 30 баллов. Срок выполнения --- 1 неделя (прислать по e-mail). За каждое домашнее задание можно получить 10 баллов. За сданное в срок задание один дополнительный балл (т.е. 33 баллов за 3 правильных задания в срок). Минимальный набор файлов в решенном задании --- это отчет и код.

- [Критерии оценки домашних заданий](evaluation_criteria.html)
- [Пример решения домашнего задания](example-report.zip)
- [Правила хорошего кода](coding_practices.html)

(3) В конце курса будет финальный тест --- 38 баллов (всего 19 вопросов, каждый правильный ответ приносит 2 балла).

Итоговая оценка:

- Выше 60 баллов - зачет
- 60-69 баллов => «удовлетворительно»; 70-79% => «хорошо»; 80 и больше => «отлично»

### Пересдачи заданий

По пропущенным темам будут дополнительные вопросы в тесте в конце курса.

<!--

- [Как и где можно найти помощь с R и статистикой](more_help.html)

-->
