---
title: Презентации и данные
---

## 1.Знакомство с R 

```{r eval=FALSE}
install.packages("ggplot2")
```

- Конспект [html](01_intro_to_r.html)
- [код R](01_intro_to_r.R)
- [Примеры вопросов следующего теста]


## 2.Анализ мощности

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Примеры вопросов следующего теста]

## 3.Регрессионный анализ, часть 1

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Примеры вопросов следующего теста]

## 4.Регрессионный анализ, часть 2

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Домашнее задание №2]
- [Примеры вопросов следующего теста]

## 5.Дисперсионный анализ, часть 1 

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Примеры вопросов следующего теста]

## 6.Дисперсионный анализ, часть 2.

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Домашнее задание №3] (выберите себе один из вариантов)
- [Примеры вопросов следующего теста]

## 7.Анализ главных компонент

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Примеры вопросов следующего теста]

## 8.Дискриминантный анализ 

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Домашнее задание №3]
- [Примеры вопросов следующего теста]

## 9.Ординация и классификация с использованием мер сходства-различия

- Презентация [html] | [pdf]
- [код R]
- Данные
- [Примеры вопросов следующего теста]
